### ISSUE TITLE
An exception has been thrown during the rendering of a template ("SQLSTATE[42S22]: Column not found: 1054 Unknown column 'posts_count'

### ISSUE THREAD

**Issue by haralake** [GinoPane/oc-blogtaxonomy-plugin#10]
### Expected behaviour
Create a partial with "Tag List" and call it in a Page
### Actual behaviour
When you call the Page with the partial you get this error message:

An exception has been thrown during the rendering of a template ("SQLSTATE[42S22]: Column not found: 1054 Unknown column 'posts_count' in 'where clause' (SQL: select `ginopane_blogtaxonomy_tags`.*, (select count(*) from `rainlab_blog_posts` inner join `ginopane_blogtaxonomy_post_tag` on `rainlab_blog_posts`.`id` = `ginopane_blogtaxonomy_post_tag`.`post_id` where `ginopane_blogtaxonomy_tags`.`id` = `ginopane_blogtaxonomy_post_tag`.`tag_id` and `published` is not null and `published` = 1 and `published_at` is not null and `published_at` < 2019-02-08 11:55:52) as `posts_count` from `ginopane_blogtaxonomy_tags` where `posts_count` > 0)") in "/mnt/c/Projects/www/octobercms1/themes/rainlab-vanilla/pages/blog.htm" at line 7.

### Steps to reproduce the behaviour
On Octobercms with installed Blog plugin create a partial with Tag List component and call it in Blog Page. Now call the page and you get the error. Test it in local environment on 2 different installs.

**Comment by GinoPane** [comment]
Hi!
Just to be sure, do you use the latest versions of blog plugin and of this one?

**Comment by haralake** [comment]
Yes is the latest one.

**Comment by GinoPane** [comment]
The problem is that I haven't reproduced this yet, no error for me:

![image](https://user-images.githubusercontent.com/3897579/52484950-709b2e00-2baf-11e9-945c-ac047d81cfcd.png)

Could you please also show your component configuration?

**Comment by haralake** [comment]
![screenshot_3](https://user-images.githubusercontent.com/18325407/52485366-6124e080-2bc1-11e9-8302-b7a5bc12112c.png)
![screenshot_5](https://user-images.githubusercontent.com/18325407/52485367-61bd7700-2bc1-11e9-9a91-9b66ea686ea3.png)
![screenshot_2](https://user-images.githubusercontent.com/18325407/52485368-61bd7700-2bc1-11e9-973b-d1d88ab30146.png)

**Comment by GinoPane** [comment]
Sorry, one more question, what DB do you use?

**Comment by haralake** [comment]
Hi! I use InnoDB (utf8mb4_unicode_ci)

**Comment by GinoPane** [comment]
Ok, finally I got this. It can be reproduced using MySQL for example, but no error for SQLite.

Thanks for reporting this, I'll work on solution.

**Comment by haralake** [comment]
Oh, that is my fault. I didn't tell you that i use MySQL. The good is that you finally reproduced it. I will wait for next update that fixes this issue.

**Comment by GinoPane** [comment]
@haralake could you please try the latest version?
I've released 1.5.1 which should fix the issue.

**Comment by haralake** [comment]
Yes now is working! Thank you for the fix.
