### ISSUE TITLE
"No tags found message" when i use tag list on category page.

### ISSUE THREAD

**Issue by haralake** [GinoPane/oc-blogtaxonomy-plugin#11]
### Expected behaviour
Tag list view on category page
### Actual behaviour
"No tags found message" when i use tag list on category page.
### Steps to reproduce the behaviour
Create tag list component and call it on blog category page. "No tags found message" will be shown.

**Comment by GinoPane** [comment]
Hi!
What is your configuration for the component?
If you have "display empty" unchecked, your component will show only tags with posts. So make sure that you either check the option or assign some tags to posts.
Also, check your "post slug" option, maybe it is the same as your category slug, and the component tries to use it for filtering and therefore it can't find anything. You can set that option to something irrelevant (like "-") if you want to disable that filter. Maybe I'll set it to something irrelevant by default in the future update for better user experience.
Anyway, please check your settings. I think you'll get your tags☺
And please refer to the readme, options are explained there.

**Comment by haralake** [comment]
Tags component works ok in page with post list, is working ok also in page with tag post list, but in category page gives 0 tags even if category has posts with tags. I'm using Vanilla Rainlab Theme and i will send you my components settings. If i change slug on categories for example i will lose category name on my links and this is something wrong. I use to have other tag component that working without any issues with categories slug option, but taxonomy has way better implementation and more features so i try to find a way to keep my categories slug on my links and also have the component tags to work.
![screenshot_2](https://user-images.githubusercontent.com/18325407/52520777-2335c400-2c76-11e9-9e93-12fa57c0afed.png)
![screenshot_3](https://user-images.githubusercontent.com/18325407/52520778-23ce5a80-2c76-11e9-8ea3-fbe0417864ed.png)
![screenshot_4](https://user-images.githubusercontent.com/18325407/52520779-23ce5a80-2c76-11e9-98aa-f631208b049e.png)

**Comment by GinoPane** [comment]
Please try to change post slug option on your tag component, not on the category component.

**Comment by haralake** [comment]
Now i see it. I only use post slug ":slug" on Post Page to display only tags of the specific post. And i change it on Category page to display tags for all posts. Thank you.

**Comment by GinoPane** [comment]
Yep, exactly, you should use differently configured components for special cases.
