### ISSUE TITLE
Validation Fails for Non-latin Alphabets 

### ISSUE THREAD

**Issue by exaline-ru** [GinoPane/oc-blogtaxonomy-plugin#14]
Hello! My Blog Taxonomy plugin does not want to add a tag and a series in Russian (as the main language of the site). Can this be eliminated or not? (the Translate plugin is also installed, but it doesn't help).

**Comment by GinoPane** [comment]
Hi!
Is your issue related to this validation error?

![image](https://user-images.githubusercontent.com/3897579/53483791-2e606080-3a7a-11e9-9982-351443fdbbb1.png)

Silly me, for some reason I haven't checked that. Will be fixed.

**Comment by exaline-ru** [comment]
Yes. But suppose, and if it is added, the search will work with them !?

**Comment by GinoPane** [comment]
I suppose the search is done via some third-party plugin, so it is better to check with that.

If you mean using translated tags/series in URL as slugs, then it would work fine.

**Comment by exaline-ru** [comment]
The servant must remain in Latin. It will be ok. If the search will work with Russian tags when displaying content by these tags, it will be great.

**Comment by exaline-ru** [comment]
Patch does not work!

**Comment by GinoPane** [comment]
The patch has not been done yet 😄 
Don't worry, I'll notify you when it's out.

**Comment by GinoPane** [comment]
Regarding search it all depends on what plugin (and component from that plugin) you use for the search. Components from this plugin works fine with translated tags and series.

**Comment by exaline-ru** [comment]
A bit in a hurry. Excuse me!

**Comment by GinoPane** [comment]
Please check now, 1.5.2 version should be available.

**Comment by exaline-ru** [comment]
It worked! Thank you very much for your promptness.

**Comment by GinoPane** [comment]
No worries.
Thankfully to your report I've discovered an issue with translatable plugin (it does not pick any validation rules for non-primary languages actually).

**Comment by GinoPane** [comment]
Don't hesitate to post a positive rating on marketplace if you like your experience 😏
