### ISSUE TITLE
No link between tags with tag section

### ISSUE THREAD

**Issue by exaline-ru** [GinoPane/oc-blogtaxonomy-plugin#15]
No link between tags with tag section.

![kHMdl45dKT](https://user-images.githubusercontent.com/46493161/54084429-926c0a00-4341-11e9-821c-bd266ad2b6ff.png)
![yT5dAvJWFu](https://user-images.githubusercontent.com/46493161/54084431-96982780-4341-11e9-814f-26f2cbf38316.png)

**Comment by GinoPane** [comment]
Hi! Could you please explain what you mean?
Tags from the first screenshot will appear in the list when you save your post. And vice versa - if you update the list and add more tags, they will appear in taxonomy tab for population.
Also, I see you have another "Tags" tab on the first screenshot. Is it possible, that tags from the second screenshot belongs to that tab (I assume you have another plugin for tags and it may conflict).

**Comment by exaline-ru** [comment]
I mean that the tags are not saved in the tags section, although it should be.

**Comment by GinoPane** [comment]
I'm quite sure they do. What I can suggest for investigation:
1) Please check another plugin that you use for tags, try to uninstall it.
2) If you have access to DB, please check the "ginopane_blogtaxonomy_tags" table and see which tags are really saved.

**Comment by exaline-ru** [comment]
Not saved!
![lYbis9JmKO](https://user-images.githubusercontent.com/46493161/54085912-44accd00-4354-11e9-95a1-20e4c6992b6f.png)

**Comment by GinoPane** [comment]
That's really strange, I cannot reproduce this. Everything is fine and all tags can be saved for me.

Do you still have the same issue? What about another plugin, have you tried to uninstall it? If you could provide more details, it would be really helpful (did it work before, when did it start to fail, what did you do when it started to fail, etc.)

**Comment by exaline-ru** [comment]
The problem of not storing tags is eliminated by removing the extraneous plug-in (Blog tags). But the Related Posts component works with an error.
![Kioae8bMVQ](https://user-images.githubusercontent.com/46493161/54086746-5e9edd80-435d-11e9-8eec-b3348f6786ea.png)
![8RN6bGOUFX](https://user-images.githubusercontent.com/46493161/54086749-6494be80-435d-11e9-8bed-182f42807481.png)

**Comment by GinoPane** [comment]
Nice!

The same question for this error. Was `relatedPosts` component installed when you had that another plugin or after, when the plugin had been removed already? It is not reproducible for me either, so I suspect it may be connected.

If possible, could you also post the rest of the screen where the trace of the exception is shown?

**Comment by exaline-ru** [comment]
Posts with the tags too with errors similar!
![Exception_-_2019-03-10_19 05 23](https://user-images.githubusercontent.com/46493161/54087778-b80c0a00-4367-11e9-8aba-64c8bbea3563.png)

**Comment by GinoPane** [comment]
Thanks!

![image](https://user-images.githubusercontent.com/3897579/54087812-1b963780-4368-11e9-93d7-f157de4db5ab.png)

The line when the error is thrown is in blog views plugin: https://octobercms.com/plugin/vdomah-blogviews

**Comment by exaline-ru** [comment]
Thank you very much! All errors are resolved.

**Comment by GinoPane** [comment]
No worries! 
I'm glad that it is fine now 😄

**Comment by exaline-ru** [comment]
In which files will I be able to customize the content show forms?

**Comment by GinoPane** [comment]
I'm afraid this is irrelevant to the plugin 😏 

Do you mean how to customize the component markdown? **If yes**, there are several ways to do that. One of them is to put it's markdown into your page content:

![image](https://user-images.githubusercontent.com/3897579/54088426-0244b980-436f-11e9-8303-f9ac4eb12501.png)

When the cursor is on "component" word a small icon appears (on the right). If you click on it the component's markdown will be injected into your page, so you could edit it as you want.

**Comment by exaline-ru** [comment]
I did it in a purple line. But the mistake came out.
![iAQy51MuhV](https://user-images.githubusercontent.com/46493161/54088563-6916a280-4370-11e9-8209-b9b4bddfd543.png)

**Comment by GinoPane** [comment]
Please don't forget that this is not a OctoberCms support forum 😄 

In this case `partial '@list'` means that the partial is related to the plugin's root, and not your theme's root, that's why such case must be replaced with a specific component reference, like this:

`{% partial postsInSeries ~ "::list" %}`

and

`{% partial postsInSeries ~ "::pagination" %}`

**Comment by exaline-ru** [comment]
Thank you! If there would be documentation... Sorry for not the convenience!

**Comment by GinoPane** [comment]
No worries.

Yes, the documentation could be useless sometimes, it is not so easy to find exact solutions there. Anyway, I've released 1.5.3 a moment ago and it does a small tweak, so October could resolve those partials automatically, so you don't need to write those lines of code manually.
