### ISSUE TITLE
Bug in pagination page

### ISSUE THREAD

**Issue by exaline-ru** [GinoPane/oc-blogtaxonomy-plugin#16]
Bug in pagination page:
![sNVHlkbtjN](https://user-images.githubusercontent.com/46493161/54232581-0235ec80-451c-11e9-82c2-4578dd313038.png)

**Comment by GinoPane** [comment]
Hi! Could you please provide more info so I could investigate?
1) Your posts in series page markup.
2) Posts in series component config.

**Comment by GinoPane** [comment]
FYI the default pagination included into this plugin is a basic AJAX pagination, so the link shouldn't include anything actually, all data is passed via attributes. If you "inspect" the source of the page you would see something like this:

![image](https://user-images.githubusercontent.com/3897579/54258271-0aad1800-455a-11e9-97a2-86d53d2b3154.png)

If you need a simple pagination without AJAX or AJAX pagination does not work for any reason you'll need to override the pagination partial and make your own markdown.

Maybe I'll include the basic non-ajax pagination and make a toggle to choose but it is hasn't been prioritized yet.

**Comment by exaline-ru** [comment]
You have correctly described the error! What is the simplest solution for this? (In principle, the default setting should work by itself).

**Comment by GinoPane** [comment]
Sorry, but I haven't described any errors, my screenshot shows how it supposed to be 😄 So I still don't understand what does not work for you.
Could you please answer the questions I posted above?

**Comment by exaline-ru** [comment]
![bQCn1wdTid](https://user-images.githubusercontent.com/46493161/54345431-1977f580-4654-11e9-878a-f518655f00ce.png)

**Comment by GinoPane** [comment]
As I have said it would be nice if you could provide any relevant details. I assume you have changed something in the template.
I have no issues with this page in default state (except it's ugly markdown, but it is only an example):

![series_demo](https://user-images.githubusercontent.com/3897579/54348111-4e7a4d00-4640-11e9-9a6c-e0183fe0782e.gif)

**Comment by exaline-ru** [comment]
I can send you a link to my site in PM!? (This is currently only a test version of the site, and not for the public).

**Comment by GinoPane** [comment]
I advise to you not to do that, it is not safe 😄
All you need to do is to answer questions from yesterday:

1) What happens when you click on the link?
2) What is your "posts in series" page markup.
3) postsInSeries component config.

**Comment by exaline-ru** [comment]
Причина очень простая: котовый файле в вашем плагине по адресу: /plugins/ginopane/blogtaxonomy/components/partials/pagination.htm
не работает (по умолчанию). Его надо редактировать, чтобы сработало! Мне это можно делать когда время будет. Но плагин должен работать и без этого вмешательства. Если вы желаете совершенствовать свой плагин, то стоит обратить внимание на это. Спасибо за внимание.

**Comment by GinoPane** [comment]
Ok, I'll post this again:

![image](https://user-images.githubusercontent.com/3897579/54357493-20076c80-4656-11e9-90b3-8d7119ca41e1.png)

This is default page with default partial which obviously works.

If it does not work for some reason in your case, you should provide details of how you use the plugin and the component. How can I help you if you don't give any details?

**Comment by exaline-ru** [comment]
![1](https://user-images.githubusercontent.com/46493161/54374380-0e42bb00-4690-11e9-82eb-3e7fc718ebcd.png)
![2](https://user-images.githubusercontent.com/46493161/54374383-126ed880-4690-11e9-948e-c25dfe305d32.png)
![3](https://user-images.githubusercontent.com/46493161/54374391-169af600-4690-11e9-867d-cc692f783092.png)

**Comment by GinoPane** [comment]
@exaline-ru Yep, nothing special there. What about the markup?

![image](https://user-images.githubusercontent.com/3897579/54375962-14866680-4693-11e9-99ef-9e7eff64e98e.png)

**Comment by exaline-ru** [comment]
`<h1>{{ "ginopane.blogtaxonomy::lang.components.series_posts.posts_in_series" | trans }} "{{ postsInSeries.series.title }}"</h1>

{% if postsInSeries.series.featured_images.count %}
    {% for image in postsInSeries.series.featured_images  %}
        <img
            title="{{ image.title }}"
            src="{{post.custom_fields.featured_image|media}}"
            alt="{{ image.description }}"
            style="width:200px;height:auto;"
        />
    {% endfor %}
{% endif %}

{% if postsInSeries.posts %}
    <ul id="{{ postsInSeries.alias }}-list">
        {% partial postsInSeries ~ "::list" %}
    </ul>

    <nav id="{{ postsInSeries.alias }}-pagination">
        {% partial postsInSeries ~ "::pagination" %}
    </nav>
{% else %}
    {{ "ginopane.blogtaxonomy::lang.components.series_posts.no_posts_message" | trans }}
{% endif %}`

**Comment by GinoPane** [comment]
Hm, there was an error in that code that you posted before the image (`<ul id="{{ __SELF__.alias }}-list"></ul>` was missing and it could explain the issue), but the code on image looks fine.

Ok if you still want to let me try myself you can send url and credentials here: sam-loaf@yandex.com and I'll take a look.

**Comment by GinoPane** [comment]
Or you could try to put this instead of your current pagination (this is a basic not AJAX version):

    <nav id="{{ postsInSeries.alias }}-pagination">
        <div>
            {{ "ginopane.blogtaxonomy::lang.components.partials.displaying_number_of_posts" | trans | format(postsInSeries.posts|length, postsInSeries.posts.total)}}
        </div>

        {% if postsInSeries.posts.lastPage != 1 %}
        <div>
            {{ "ginopane.blogtaxonomy::lang.components.partials.viewing_page_of" | trans | format(postsInSeries.posts.currentPage, postsInSeries.posts.lastPage)}}
        </div>
        <div>
            {% if postsInSeries.posts.currentPage > 1 %}
            <a href="{{ '' | page({ page: postsInSeries.posts.currentPage - 1 }) }}">
                &lt; {{ "ginopane.blogtaxonomy::lang.components.partials.pagination_back" | trans }}
            </a>
            {% endif %}

            {% if postsInSeries.posts.currentPage < postsInSeries.posts.lastPage %}
            <a href="{{ '' | page({ page: postsInSeries.posts.currentPage + 1 }) }}">
                {{ "ginopane.blogtaxonomy::lang.components.partials.pagination_next" | trans }} &gt;
            </a>
            {% endif %}
        </div>
        {% endif %}
    </nav>

**Comment by exaline-ru** [comment]
It worked!

**Comment by GinoPane** [comment]
This is totally strange. The code you posted on the screenshot should be working too - I have the same. Unless something else was changed somewhere 🤷‍♂️
