### ISSUE TITLE
Filter tag/series post list by post/category

### ISSUE THREAD

**Issue by exaline-ru** [GinoPane/oc-blogtaxonomy-plugin#32]
Display tags only for a specific category. How to implement?

Goal: Limit a large number of tags to a variety of categories.

**Comment by GinoPane** [comment]
Hi @exaline-ru !

Could you please explain what is your use-case?

Tags are assigned to posts and therefore tags don't have any category reference.
It sounds more like a specific logic for your application and not something generic that should be included into this plugin.

Tag list component can be filtered by Post though, could it be useful for you?

**Comment by exaline-ru** [comment]
It is possible to form a question differently: How to hide blog post by Except categories!? Now blog post in Except categories are displayed in posts in the series.

**Comment by GinoPane** [comment]
@exaline-ru so you'd like to have something similar as for post list component from Rainlab/Blog?

![image](https://user-images.githubusercontent.com/3897579/58341148-76a6d900-7e45-11e9-9667-c296314e164e.png)

**Comment by exaline-ru** [comment]
Regarding this question: right now the number is displayed correctly on only published blogs.
https://i.imgur.com/ATCSQ7t.png
But there was a consistent question: how to hide the category (if the blog category sheet is hidden respectively) blog in the series sheet?

**Comment by GinoPane** [comment]
@exaline-ru so, the component you are showing on the screenshot is used to get the list of posts in series. And now it can be additionally filtered by category/post.

Do you want the same functionality for:
![image](https://user-images.githubusercontent.com/3897579/58876503-386fac00-86c6-11e9-82e0-f0e6508d54e0.png)

So you could get the number of posts in series using exceptions?

**Comment by exaline-ru** [comment]
Apparently, the blog plugin has the same problem - there is no filter in the hidden categories.
![image](https://user-images.githubusercontent.com/46493161/58878010-e7b67e00-86da-11e9-9548-826be878dffd.png)

**Comment by GinoPane** [comment]
@exaline-ru so did I get you right? :smile: 
Yes, blog plugin does not have such feature for its categories list

**Comment by GinoPane** [comment]
Released as Blog Taxonomy 1.11.0

**Comment by GinoPane** [comment]
Exclusions were implemented for tag/series lists

**Comment by HitArrowLegend** [comment]
Sorry to reopen this, but could you add a way to filter the tags per category? 

The use would be to have a component displaying all the articles (the category) from the specified tag. It would also allow us to have fully fleshed out tag pages, as we could organize the articles showing up on the tag list page.

We can exclude categories already so it's not a deal breaker as we can just decide to exclude all the other categories instead. It wouls save some time if you have tons of categories though.

![chrome_w4PlULOOBY](https://user-images.githubusercontent.com/2132234/82268707-f770b600-996f-11ea-8176-0ece755bffcc.png)

**Comment by GinoPane** [comment]
@HitArrowLegend yep, I think it's doable

**Comment by GinoPane** [comment]
@HitArrowLegend please check the version 2.1.1
