### ISSUE TITLE
Series Page and Related Series

### ISSUE THREAD

**Issue by djshadow** [GinoPane/oc-blogtaxonomy-plugin#34]
How do I display a single series page like how it's done in blogSeries plugin?

The same goes for how to display related series inside the single series page?

I just need these two fixed to make the plugin perfect.

Thank you.

**Comment by GinoPane** [comment]
Hi! 
I've responded to you in email already 😄 

Anyway, regarding your first question, here's how components between two plugins can be mapped:
![image](https://user-images.githubusercontent.com/3897579/58433961-0d7fc980-80c2-11e9-90e0-e3e9b5ade896.png)

I believe, you used `blogSeries` component to show a single series page, so the same can be done using `postsInSeries` component from the "Blog Taxonomy".

One problem though - this plugin does not have related series support at the moment. But I agree - it sounds useful. Unfortunately nobody requested this feature before and I didn't need it either 😄 

But I can consider implementing for this plugin.

**Comment by djshadow** [comment]
Thanks for responding, but the postsInSeries component when used the series page redirects me to a 404 page. I've used all the other components and none seems to do the trick. :(

**Comment by GinoPane** [comment]
I assume that something is wrong with configuration you set for it, or with the data. Could you please provide your config?

**Comment by djshadow** [comment]
![2019-05-28](https://user-images.githubusercontent.com/2495820/58462640-ce816080-8121-11e9-9189-faca16c52eb8.png)

**Comment by GinoPane** [comment]
@djshadow did you have the same page configuration before? Your URL seems to be pretty global. 
Also, is the link correct for the page that gives you 404 error?
Also, if you are able to debug the code you could check plugins/ginopane/blogtaxonomy/components/SeriesPosts.php::prepareContextItem to see if the system actually comes there.

The component itself obviously works fine if everything else is correct.

**Comment by djshadow** [comment]
It's the same URL that works fine with that other plugin, so I don't see how it should be the issue here.
The link is correct too. The series and posts links are on the front page so when clicked it goes to the correct page if the other plugin is used the page loads but when I use yours it redirects to 404 page.

Hope I can figure this thing out.

**Comment by GinoPane** [comment]
@djshadow it's strange then, better to check that file from above. I assume that for any reason slug does not come to the component.

**Comment by GinoPane** [comment]
Also, if you haven't done this already, try to disable another plugin.

**Comment by djshadow** [comment]
Ok let's try that too and see. :)

**Comment by djshadow** [comment]
Hmm, broke the whole site. If I was that good with coding I would have looked into this better. Sorry for the trouble but I will have to leave this for now I think. :(

**Comment by GinoPane** [comment]
@djshadow oops :smile: Plugin disabling can break something if your pages still have components from that plugin. I suggest you to try on another clean page then if you still have both plugins installed. Or even play on another October installation if possible.

**Comment by GinoPane** [comment]
This one has been released as Blog Taxonomy 1.11.0

**Comment by GinoPane** [comment]
@djshadow migration functionality has been released in 1.12.0

**Comment by djshadow** [comment]
I've disabled that other plugin and some other plugins before I got yours to work. Seems like some new updates from other plugins just broke so many stuff.

How do you get images from the series to be displayed inside a blog post? What component should I add and what code will make it work?

Great work so far. I really appreciate all the time and effort you've put into this.

**Comment by GinoPane** [comment]
@djshadow what exactly do you want to achieve?

Series model has featured_images attached, so if you have series, you'd be able to access its images.
Do you need to get a series that is attached to a specific post?

**Comment by djshadow** [comment]
Something like a post page, which has a specific series already attached to it. The series has a featured_image uploaded, so I want that featured_image from the series displayed on that post page.
Do I use the post in the series component or post series navigation component? And depending on which one I use, what line of code will pull up the desired featured_image?

Hope you get what I'm trying to achieve?

Thank you.

**Comment by GinoPane** [comment]
@djshadow so yes, you can use "Post Series Navigartion". It will give you the list of posts in the series for current post and the current post will be marked as active, like this:

![image](https://user-images.githubusercontent.com/3897579/60196987-23121b80-9847-11e9-8c31-e337b9e5550e.png)

If you expand the component's markup you'll get this:

![image](https://user-images.githubusercontent.com/3897579/60197067-56ed4100-9847-11e9-910d-fe600c0787c6.png)
![image](https://user-images.githubusercontent.com/3897579/60197084-640a3000-9847-11e9-8a61-1f553b3f3fba.png)

So the series object is available there. And if you add there something like:

        {% if seriesNavigation.series.featured_images.count %}

            <div>
                {% for image in seriesNavigation.series.featured_images %}
                    <div>
                        <img src="{{ image.path }}" alt="{{ image.title }}" style="width: 10vw">
                    </div>
                {% endfor %}
            </div>

        {% endif %} 

on the frontend you'll get:

![image](https://user-images.githubusercontent.com/3897579/60197161-9025b100-9847-11e9-91e2-d567b0261085.png)

The series itself has these images in its config:

![image](https://user-images.githubusercontent.com/3897579/60197248-bba89b80-9847-11e9-98de-2909c02d81f2.png)

**Comment by djshadow** [comment]
Great, that is what I was looking for. Thanks, this solved an issue for me. 👍
