### ISSUE TITLE
[BUG] Error update to last version

### ISSUE THREAD

**Issue by exaline-ru** [GinoPane/oc-blogtaxonomy-plugin#38]
Update failed

"SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'ginopane_blogtaxonomy_related_series' already exists (SQL: create table `ginopane_blogtaxonomy_related_series` (`series_id` int unsigned not null, `related_series_id` int unsigned not null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)" on line 664 of /home/admin/web/domain.com/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php

**Comment by exaline-ru** [comment]
Version 1.11.0

**Comment by GinoPane** [comment]
@exaline-ru this is because you have already created that table on your own probably (actually I had the same error because I had that table already during development :smile: ).
All other users won't have that table and therefore won't have the error. If you have configured any related series already, I'd suggest to rename the table for now, install update, remove the new table, and rename your old table back.

**Comment by exaline-ru** [comment]
This table did not create, in MySQL did not change anything except the automatic update! The previous update went fine.

**Comment by StanleyBonhomme** [comment]
Im having the same issue.

**Comment by GinoPane** [comment]
@exaline-ru, @StanleyBonhomme that's so strange... The only place where the table is created is the update script, which October should call only once. And therefore either it was called twice for no reason, or the table was created before. I'll try to reproduce it in my environment.

**Comment by GinoPane** [comment]
I've uninstalled and installed the plugin again - no issues.
Reverted to 1.5.4 with Builder plugin and updated to the latest version - no issues.

Here's the output of the plugin:refresh command:

![image](https://user-images.githubusercontent.com/3897579/59376894-b9c7de00-8d59-11e9-8b59-0379f02f0c58.png)

Again, no issues.

It would be great if you could provide any details that could help understand, why you have the issue.

**Comment by exaline-ru** [comment]
When changing the name of the table (where the error is indicated), the update did not go. Same mistake!
Even after deleting the table: ginopane_blogtaxonomy_related_series - The same mistake came out.
Can you send me only file sql to import into the database !?

**Comment by GinoPane** [comment]
@exaline-ru Please try with the latest version (1.11.1) that has been released a few minutes ago. As I've said I cannot reproduce the issue, but I tried to update what could potentially help.

**Comment by exaline-ru** [comment]
Update version 1.11.1 was successful!
