### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by schwenks** [GinoPane/oc-blogtaxonomy-plugin#53]
Hi,

I would like to use your plugin. But I get the following error on installation:

PDOException: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'ginopane_blogtaxonomy_taggables_tag_id_ginopane_blogtaxonomy_taggable_id_ginopane_blogtaxonomy_tagga' is too long in [...]/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105

Could you habe a look?

Thanks

Soenke

**Comment by GinoPane** [comment]
Hi!

Ahh, yep, I'm looking into this, thanks for reporting!

**Comment by GinoPane** [comment]
@schwenks please check now, the 2.0.1 version has been released

**Comment by schwenks** [comment]
Hi,

that was fast.  Sadly I now get a
"SQLSTATE[HY000]: General error: 1005 Can't create table `october`.`ginopane_blogtaxonomy_taggables` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `ginopane_blogtaxonomy_taggables` add constraint `Tag reference` foreign key (`tag_id`) references `ginopane_blogtaxonomy_tags` (`id`) on delete cascade)" on line 664 of [...]/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php

**Comment by exaline-ru** [comment]
After last update I have this critical error:
```
We're sorry, but an unhandled error occurred. Please see the details below.

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'series_count' in 'having clause' (SQL: select `ginopane_blogtaxonomy_series`.*, (select count(*) from `rainlab_blog_posts` where `ginopane_blogtaxonomy_series`.`id` = `rainlab_blog_posts`.`ginopane_blogtaxonomy_series_id` and `published` is not null and `published` = 1 and `published_at` is not null and `published_at` < 2020-01-15 07:49:21) as `posts_count` from `ginopane_blogtaxonomy_series` group by `id` having `posts_count` > 0 or `series_count` > 0 order by `title` asc)
/home/admin/web/exaline.ru/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php line 664
```

**Comment by GinoPane** [comment]
@schwenks, @exaline-ru do you both use MySQL, right?

**Comment by exaline-ru** [comment]
> @schwenks, @exaline-ru do you both use MySQL, right?

Yes.

**Comment by GinoPane** [comment]
@exaline-ru @schwenks please check now, a new version has been pushed.

**Comment by exaline-ru** [comment]
The issue is resolved! Thanks.

**Comment by GinoPane** [comment]
@exaline-ru cool, thanks for reporting!

**Comment by exaline-ru** [comment]
All tags were erased. On the next update-please be careful, especially with MySql.

**Comment by schwenks** [comment]
Sorry for the late response. It is working for me now. Thank you.

**Comment by GinoPane** [comment]
@exaline-ru nothing was erased actually, the old table is still there. 

Was new table `ginopane_blogtaxonomy_taggable` table filled for you? Because it should be filled with your current tags. Did you experience any issues during the update itself?

**Comment by exaline-ru** [comment]
There was a mistake in the update, but I pressed the button again and the update was done. Later only noticed that all the tags had disappeared.

**Comment by GinoPane** [comment]
@exaline-ru that's really strange, sorry to hear that.

All your tags are still in the DB if you check it directly (_ginopane_blogtaxonomy_post_tags_ table). I could suggest to rollback to the latest 1.x version and then update again. Or go to DB and move tag relations to a new table manually. Currently your tag relations are in the table _ginopane_blogtaxonomy_post_tags_ and now they need to be moved into another one:

![image](https://user-images.githubusercontent.com/3897579/72467044-32f54b00-37eb-11ea-834b-a5c980c1066c.png)

It looks like this inside:
![image](https://user-images.githubusercontent.com/3897579/72467225-8bc4e380-37eb-11ea-89ea-0a79399200eb.png)

Normally this should happen during the update so ideally the user shouldn't notice anything.

**Comment by exaline-ru** [comment]
Restored tags according to your instructions in the manual version. Thanks!
