### ISSUE TITLE
[BUG] The tag URL of the Component tagList is incorrect

### ISSUE THREAD

**Issue by alpha-97** [GinoPane/oc-blogtaxonomy-plugin#59]
**Describe the bug**

The tag URL of the Component tagList is incorrect, I have tried to fix it and it works.
Hope the fix will be included in the next release after your review, Thanks.

ginopane/blogtaxonomy/components/TagList.php
Line 367

current:
$this->setUrls($tags, $this->tagPage, $this->controller, ['tag' => $this->urlProperty($tagComponent, 'tag')]);

suppose to be:
$this->setUrls($tags, $this->tagPage, $this->controller, ['tag' => $this->urlProperty($tagComponent, 'slug')]);

**To Reproduce**
1. Use the Component tagList
2. Click on the Tag link
3. Wrong URL poped
...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by GinoPane** [comment]
Hi @alpha-97 ! Thanks for reaching out!

That link is built for the page 

Could you please tell which config do you use for the page where the postWithTheTag

**Comment by alpha-97** [comment]
Many Thanks GinoPane for your prompt reply.

Could you please share how that component is configured on your side?
=> I just created the "Tag Post" page and link it to the component tagList without setting up the "Tag Post" page with the "postwithtags" component, and this will lead to the inorrect link.

After I put the "postwithtags" component to the "Tag Post" page, the URL of the Component tagList works. ^_^

**Comment by GinoPane** [comment]
@alpha-97 Hi! I'm glad it helped.

This is the point of the link - to lead to the page with the component which can show anything useful for that tag or series. If the destination page is not set the component simply does not have enough data to generate the link.
