### ISSUE TITLE
SQLSTATE[42S22] column not found 1054 unknown column error

### ISSUE THREAD

**Issue by malachiman** [GinoPane/oc-blogtaxonomy-plugin#6]
### Expected behaviour
Be able to save a new blog post. 
### Actual behaviour
Displays error unknown columns 
### Steps to reproduce the behaviour
I had this working very well on a local development site.  I then installed it on an existing websites. The error only displays on this site.  I can uninstall Blog Taxonomy and the RainLab Blog works fine, posts will save,  If I reinstall Taxonomy I get the error again and unable to save a post.    I can create and save series fine, just can’t save posts.

**Comment by GinoPane** [comment]
If you have access to your database you can check required tables/columns were actually created. Maybe for some reason October didn't run migrations, so you can try to rerun them from command line like this (from october directory):
`php artisan plugin:refresh ginopane.blogtaxonomy`

**Comment by malachiman** [comment]
I have attached a screen shot of the error.  I have uninstalled Blog Taxonomy and reinstalled it, same error.  

<img width="541" alt="screenshot 01" src="https://user-images.githubusercontent.com/37282159/51319348-a6be2400-1ac1-11e9-8c21-4dde1b877762.png">

**Comment by GinoPane** [comment]
Oh, as you can see, the column is **seo_title**, this does not belong to Blog Taxonomy plugin.

**Comment by malachiman** [comment]
Oh right, I just realised this build has 'SEO Extension' installed.  The local site I was testing on didn't have it installed.

**Comment by malachiman** [comment]
So what will be my way around this, do you have any suggestions?

**Comment by GinoPane** [comment]
You can probably try to reinstall 'SEO Extension' then if its fields are missing for some reason.

**Comment by malachiman** [comment]
I've discovered it a massive issue with the SEO Extension, its pretty much been abandoned, and it won't uninstall properly.  Yah for that lol.    Thanks for your help. 

https://octobercms.com/plugin/support/anandpatel-seoextension/cannot-remove-plugin

**Comment by GinoPane** [comment]
No worries! 😄
