### ISSUE TITLE
[BUG] The series URL of the Component seriesList is incorrect 

### ISSUE THREAD

**Issue by alpha-97** [GinoPane/oc-blogtaxonomy-plugin#60]
The series URL of the Component seriesList is incorrect, I have tried to fix it and it works.
Hope the fix will be included in the next release after your review, Thanks.

ginopane/blogtaxonomy/components/SeriesList.php
Line 190

current:
'series' => $this->urlProperty($seriesComponent, 'series')

suppose to be:
'series' => $this->urlProperty($seriesComponent, 'slug')

To Reproduce

    Use the Component seriesList
    Click on the Series link
    Wrong URL poped

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by GinoPane** [comment]
The reason duplicates #59 and is covered there.
