### ISSUE TITLE
[FEATURE REQUEST] Support all chrs in Tag description

### ISSUE THREAD

**Issue by azrossi** [GinoPane/oc-blogtaxonomy-plugin#65]
Your plugin is great, thanks a lot!

I use Tags to group articles about restaurants in the same district in a local food blog.

A district has an apostrophe in its name.

It's perfectly reasonable to avoid special characters in the Tag slug, but why in the Tag name?

In RainLab Blog plugin, Categories name can use special chrs.

Is it possible to have this option in your plugin as well?

**Comment by GinoPane** [comment]
@azrossi Hi! Thanks!

I see no reason for not doing that. Please check out the new version 2.2.0

**Comment by azrossi** [comment]
TOP!
Thanks
