### ISSUE TITLE
"The slug field is required" message when i try to create a tag from post taglist field.

### ISSUE THREAD

**Issue by haralake** [GinoPane/oc-blogtaxonomy-plugin#7]
### Expected behaviour
Able to save tags from post taglist field. Exactly like categories field.
### Actual behaviour
"The slug field is required" error message
### Steps to reproduce the behaviour
Open a post and create a tag from taglist field, try to save changes.

**Comment by GinoPane** [comment]
Thanks for reporting this!
Fixed in 1.3.1.
