### ISSUE TITLE
[FEATURE REQUEST] - Opening / Closing Series

### ISSUE THREAD

**Issue by HitArrowLegend** [GinoPane/oc-blogtaxonomy-plugin#70]
### Pull Requests Welcome
If you can propose the implementation of some enhancement, please make a PR.

---

**Is your feature request related to a problem? Please describe.**
I'm thinking about using the blog series to cover album cycles from bands (I'm working on a progmetal/rock music news website). As far as articles goes, it usually looks like: album announcement, single 1, single 2, single 3, album release, album tour, for a total of 6 news. The problem is that with an insane amount of bands, the amount of series will quickly be enormous.

**Describe the solution you'd like**
I'd like a way to open/close the series once I don't plan to update them anymore, so that I'm not overwhelmed by previous series. Also, I'd like to be able to hide inactive series, if I want to. 
It would just be to unclogged my admin panel, as they should still work on the front end.

**Describe alternatives you've considered**
Not using series

**Additional context**
https://puu.sh/FUXNY/21e20fcfdb.png

**Comment by GinoPane** [comment]
I had an idea of different series statuses and it can solve this issue.

Are you ok with two statuses for now? Active or inactive.

**Comment by HitArrowLegend** [comment]
Yeah totally, everything that allows us not to crawl under hundreds of series is welcome :P

**Comment by GinoPane** [comment]
Please check out 2.3.0 version

**Comment by HitArrowLegend** [comment]
Amazing
