### ISSUE TITLE
How to display tag names outside of a component?

### ISSUE THREAD

**Issue by HitArrowLegend** [GinoPane/oc-blogtaxonomy-plugin#73]
Hello, 

I'm currently designing a page for all the articles with the same tags. I'm doing the header of this page and I'd like to find a way to get the name of the tag directly on the page without for loops. 

[
![image](https://user-images.githubusercontent.com/2132234/91357521-a9324500-e7f1-11ea-88eb-f2ace830995f.png)
](url)

Obviously, {{ tag.name }} renders nothing, but does Taxonomy have a thing for this kind of needs?

**Comment by GinoPane** [comment]
How does the page look like?

I mean, the current component `postsWithTag` supports filtering by one tag only. And if you look into the default template for that component you'll see:

![image](https://user-images.githubusercontent.com/3897579/91444913-11c70380-e87e-11ea-8baa-b38c3d81191e.png)

So, basically the tag would be available as `postsWithTag.tag.name` in your case.

The ability to filter by multiple tags is not available yet: https://github.com/GinoPane/oc-blogtaxonomy-plugin/issues/50.

**Comment by HitArrowLegend** [comment]
That's how my page looks like: 
![msedge_Ml8xNyTePE](https://user-images.githubusercontent.com/2132234/91485165-b2cbb380-e8aa-11ea-9521-4d6ebbc2e77b.png)

I highlighted the text to show you that nothing is added there. Here is the actual code

![msedge_PLSAfuJ9ti](https://user-images.githubusercontent.com/2132234/91485267-de4e9e00-e8aa-11ea-809d-aced7f40f928.png)

I don't know what I'm doing wrong.

**Comment by HitArrowLegend** [comment]
Nevermind, I found what I was looking for. I had to simply write {{ postsWithTag.tag.name }}. It works now

**Comment by GinoPane** [comment]
Yes, `__SELF__` works only in component partials. When you have a component's alias in place (like `postsWithTag` in your case) you should use that alias.
