### ISSUE TITLE
Exclude certain categories from the Related News component

### ISSUE THREAD

**Issue by HitArrowLegend** [GinoPane/oc-blogtaxonomy-plugin#75]
I was wondering if you could add an option to exclude categories from the Related News Component. 

Thanks

**Comment by GinoPane** [comment]
Hi!
Do you mean `RelatedPosts`?

**Comment by HitArrowLegend** [comment]
yes sorry,

**Comment by GinoPane** [comment]
Hi @HitArrowLegend! This functionality is now available in 2.5.0
