### ISSUE TITLE
[FEATURE REQUEST] Images for categories

### ISSUE THREAD

**Issue by haralake** [GinoPane/oc-blogtaxonomy-plugin#76]
Hello! A very good feature would be "**Category Images**". With a complex blog site this feature is a must have.
Thank you!

**Comment by GinoPane** [comment]
Hi!
Thanks for contacting me.
I didn't plan to add featured images for categories with this plugin because October has a nice small plugin specifically for this already. Please check out: https://octobercms.com/plugin/ribsousa-featuredimages

**Comment by haralake** [comment]
Yes i know that there is already a plugin for that purpose. There are also plugins for tags, related posts e.t.c. But your plugin is a complete solution that includes everything. That is why I think it would be ideal if it had this possibility as well.

**Comment by HitArrowLegend** [comment]
I'll add my vote, if I can call it a vote, to this request. 
It would be indeed amazing and very useful to have a way to add images to tags and series that we can call in our layouts. 
(personnelly I would need at least two images for the tags, one for cover and one for banner but one would already be plenty)

**Comment by GinoPane** [comment]
> I'll add my vote, if I can call it a vote, to this request.
> It would be indeed amazing and very useful to have a way to add images to tags and series that we can call in our layouts.
> (personnelly I would need at least two images for the tags, one for cover and one for banner but one would already be plenty)

Featured images for series are available already

**Comment by GinoPane** [comment]
I created #86 based on this. Thanks for ideas, guys. I'm closing this ticket as discussion could continue in a development story based on this one.
