### ISSUE TITLE
[FEATURE REQUEST] Include Tags Posts option in PostsInSeries Component

### ISSUE THREAD

**Issue by raelcv** [GinoPane/oc-blogtaxonomy-plugin#77]
Thanks for the plugin, this is very useful. I would just like to see this function repeat in the list of Posts in the Series.

It's just what you did for the TagPost Component for SeriesPosts:

if ($this->includeTagsPosts) {
   $query->orWhereHas('tags', function ($query) {
       $query->whereHas('series', function ($query) {
            $query->whereTranslatable('slug', $this->series->slug);
          });
      });
}

**Comment by GinoPane** [comment]
Hi! Thanks for your feedback!

Could you please describe more, when and for what this feature would be useful? As I understand, if, for example, your series has tags tag1 and tag2, you want to additionally fetch posts tagged with tag1 and tag2. Is it right? I just cannot imagine the use case when it could be useful.

Also, if you can provide a pull request for this, it would be welcome.

**Comment by raelcv** [comment]
Thanks for answering. You got it right. Perhaps my solution was not the most elegant. I'm a beginner here and I still don't know how to use the tools, so I didn't make a pull request.

I used the series to compose a tree navigation structure. Series related to other series. There is no way to make this structure with tags, it is not possible to relate tags to tags.

But at the same time, I need to repeat some posts in different series. So a better solution might be to be able to list more than one series per post. I thought this was not the purpose of the plugin. So using the tags seemed to me a practical solution to get around the problem, associating a tag to two different series.

P.s .: The use of categories was out of the question in this case.

**Comment by GinoPane** [comment]
Ok, so basically this is like "posts related to series".

**Comment by GinoPane** [comment]
I believe you didn't test you solution?

**Comment by GinoPane** [comment]
Please check for updates. The latest 2.6.0 version should be available.

**Comment by raelcv** [comment]
Thanks! Much better!
