### ISSUE TITLE
Implement post types

### ISSUE THREAD

**Issue by GinoPane** [GinoPane/oc-blogtaxonomy-plugin#87]
Based on #85 suggestion, post types could be really useful by providing sets of additional properties to the Post model.

1. Post types would be an additional model with its own backend lists, views, etc.
2. Post types would be toggleable via plugin settings. As long as post types will add additional menus, form tabs, etc. (additional complexity) they could be undesirable for those who don't need them.
3. Proposed logic: a user creates a post type, adds its name and slug, and adds a set of properties (with name, type). When creating/editing posts those types would be available for selection (one type per post). When selected, additional post properties will become available. Implementation will be done using repeater fields.

**Comment by GinoPane** [comment]
@HitArrowLegend this one is waiting for release, code changes are available on development branch

**Comment by HitArrowLegend** [comment]
Ill check that when I wake up ! Can't wait to see it in action ❤️ much love to you

**Comment by GinoPane** [comment]
I'm not so happy with the solution, I'd like to improve it, but I faced a couple of October bugs during implementation which did no allow to do what I want. Also available attribute types are a matter of discussion and feedback, I just added some for now but we can add more if needed.

**Comment by GinoPane** [comment]
> Out if curiosity before I start messing with it, can we sort posts by post type too?

Sort in some component? Or backend list?
Initial implementation does not include any of that (except probably backend post list, because I feel it is necessary to have type column there, but I haven't added it yet).

Updates to specific components are possible, but probably will be done as separated requests if required (or by pull requests if someone implements them).

**Comment by HitArrowLegend** [comment]
Aside from the fact that I don't know yet how to access and display values stored inside type_attributes (guessing it has to do with for loop but i'm not sure how to use it if that's the case), backend wise, it's pretty much how I imagined it, and the option on the blog side is great too.

**Comment by GinoPane** [comment]
@HitArrowLegend  Yes, I forgot to add it into the README, will do.
Actually, you can use `typeField(code)` or `typeFields()` methods on the Post model to get a specific field by its code (which is set when you create attributes for post types) or get all fields as an array.

In the template it looks like this:

`<span>{{ post.typeField('rating') }}</span>`

Method names are debatable. Maybe `typeAttribute(s)` is more appropriate here. I can rename it as long as the feature is not released yet.

**Comment by HitArrowLegend** [comment]
Amazing, thanks
