### ISSUE TITLE
Series Description.

### ISSUE THREAD

**Issue by malachiman** [GinoPane/oc-blogtaxonomy-plugin#9]
It seems like there is a character limit in the Series description.  Can this be opened up please.  The limit is too small.

**Comment by GinoPane** [comment]
Hi!
Thanks for reporting this!
I've changed the column type and included the changes into current release (1.5.0).

**Comment by malachiman** [comment]
Awesome, thank you. Appreciate your work.

**Comment by GinoPane** [comment]
No worries.
Please update when you can and let me know if the fix works fine. It worked for me, but who knows... 😄

**Comment by malachiman** [comment]
Yep works well now.  Also the feature image for the series is great.  Thanks.
