### ISSUE TITLE
Missing variable

### ISSUE THREAD

**Issue by enricoeur** [GinoPane/oc-blogtaxonomy-plugin#91]
https://github.com/GinoPane/oc-blogtaxonomy-plugin/blob/c9b1f2caa6443626efd0e47e4d2668cd09f42dcf/components/TagPosts.php#L80

You forgot to add **$this->page['tag']**

**Comment by GinoPane** [comment]
Hi @enricoeur!
Do you get an error? Or what are you trying to fix here?

**Comment by enricoeur** [comment]
Without that i was unable to overwrite your component style with a partial.

Because  i was unable to access tag OBJECT properties.

Il giorno dom 21 mar 2021 alle ore 16:42 Siarhei Karavai <
***@***.***> ha scritto:

**Comment by enricoeur** [comment]
In my template page i was needing to show up as title of the page the tag.name using {{ tag.name }} and without that i was unable to use, because tag object was private and not available outside the scope of your component.

**Comment by GinoPane** [comment]
Ok, that makes sense. Please use your local override if possible for now, I'll add your fix to the 3.0.0 version.
