### ISSUE TITLE
Issue when updating on existing project

### ISSUE THREAD

**Issue by HitArrowLegend** [GinoPane/oc-blogtaxonomy-plugin#94]
Hello, 

I upgraded Taxonomy on an existing project and this is what I got : 

"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp null, `updated_at` timestamp null) default cha' at line 1 (SQL: create table `ginopane_blogtaxonomy_post_types` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `slug` varchar(191) not null, `description` text null, `type_attributes` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate utf8_unicode_ci engine = InnoDB)" on line 664 of .../vendor/laravel/framework/src/Illuminate/Database/Connection.php

Any idea how to fix it ?

**Comment by HitArrowLegend** [comment]
I'm not sure, I'll have to check. The upgrade works fine on my local server tho, so it may be related to that. I'll run further tests tomorrow to make sure

**Comment by GinoPane** [comment]
I released 3.0.2 where `json` is replaced with `text`. Please let me know if it fixed the issue.

**Comment by HitArrowLegend** [comment]
It worked like a charm, thank you very much. Sorry for not getting back at you. was caught in some personal problems.
