### ISSUE TITLE
[BUG] Error when creat tag

### ISSUE THREAD

**Issue by exaline-ru** [GinoPane/oc-blogtaxonomy-plugin#98]
"Validation rule unique requires at least 1 parameters." on line 1475 of /vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php

**Comment by GinoPane** [comment]
@exaline-ru hi!

How exactly do you get this error? 

Also, which version of October do you use?

**Comment by exaline-ru** [comment]
![image](https://user-images.githubusercontent.com/46493161/118793794-9c82df00-b8a1-11eb-83cb-b8a0bcbf034b.png)

![image](https://user-images.githubusercontent.com/46493161/118793830-a4db1a00-b8a1-11eb-8030-fc3216603bde.png)

**Comment by GinoPane** [comment]
So it is version 1 right? Ok, I believe I know what's the issue

**Comment by exaline-ru** [comment]
![image](https://user-images.githubusercontent.com/46493161/118795772-9d1c7500-b8a3-11eb-8e9f-f02d0261f90b.png)

**Comment by GinoPane** [comment]
October version, not the plugin :) 

Don't worry, I'll take a look. If it blocks you somehow, just rollback to the previous version. The fix will come in the evening I believe

**Comment by GinoPane** [comment]
@exaline-ru please try on 3.1.1

**Comment by exaline-ru** [comment]
> @exaline-ru please try on 3.1.1

Thank you so much! But version 2 has a different error:
![image](https://user-images.githubusercontent.com/46493161/118962697-52b3fa80-b96e-11eb-95d7-264352e2328a.png)

**Comment by GinoPane** [comment]
@exaline-ru Hm, this is strange, because October v2 does not require anything for the "unique" rule. That's why you got the error on the v1 actually.

Make sure that you have updated the plugin, because it is the same error you got before.

![image](https://user-images.githubusercontent.com/3897579/118967534-834a6300-b973-11eb-88a4-b5d78c80b6f7.png)

![image](https://user-images.githubusercontent.com/3897579/118967581-8fcebb80-b973-11eb-86c1-41c18d4254f4.png)

![image](https://user-images.githubusercontent.com/3897579/118967704-b7258880-b973-11eb-8c35-b154f7473c87.png)

![image](https://user-images.githubusercontent.com/3897579/118967425-5dbd5980-b973-11eb-902a-56f2590dd108.png)

**Comment by GinoPane** [comment]
I've checked also on the latest 2.0.14, no issues. 
![image](https://user-images.githubusercontent.com/3897579/118968552-b9d4ad80-b974-11eb-9d06-8a05ff52bf93.png)

**Comment by exaline-ru** [comment]
I am also surprised. With version 1 we decided yesterday. See my data in 2 versions:

![image](https://user-images.githubusercontent.com/46493161/118969327-9a8a5000-b975-11eb-95c2-d4af7b466499.png)

![image](https://user-images.githubusercontent.com/46493161/118969402-ae35b680-b975-11eb-9636-8ddcbe49763f.png)

**Comment by exaline-ru** [comment]
![image](https://user-images.githubusercontent.com/46493161/118969622-f228bb80-b975-11eb-8a7b-704e639764a2.png)

**Comment by exaline-ru** [comment]
![image](https://user-images.githubusercontent.com/46493161/118969697-0a98d600-b976-11eb-8e7e-0fab0701321f.png)

**Comment by exaline-ru** [comment]
It happened after the site transfer to the 2nd version

**Comment by GinoPane** [comment]
Please check the code itself. Maybe something wrong happened during the update.

1. October v2 does not require anything for the "unique" rule. So, v2 would work nicely even with 3.1.0.
2. After the update to the 3.1.1 the argument for the "unique" rule was put back. It means that it would work on both v1 and v2.

**Comment by exaline-ru** [comment]
In the file: updates/version.yaml (Apparently with the check update in the 2 version there is a problem). After replacing the files with the last version - tag worked.

![image](https://user-images.githubusercontent.com/46493161/118976320-9104e600-b97d-11eb-91ab-62ca63e2cb94.png)
